language: cpp
sudo: required

os:
  - osx

oxs_image:
  - xcode11.3
  - xcode10.3

notifications:
  email:
    recipients:
    - dilawar.s.rajput@gmail.com
    on_success: change
    on_failure: always

script:
  - set +e
  - export PATH=/usr/local/bin:$PATH
  - brew unlink python@2
  - brew install python@3 graphviz
  - brew link --overwrite python
  - set -e
  - brew tap dilawar/moose
  - brew install moose
  - brew install -v --HEAD moose-nightly
  - /usr/local/bin/python3 -c "import moose; print(dir(moose))"
  - set +e
  - /usr/local/bin/python3 -m pip install matplotlib scipy networkx
  - /usr/local/bin/python3 -c "import moose;moose.test()"
