language: cpp
sudo: required

os:
  - osx

oxs_image:
  - xcode11.3
  - xcode10.3

notifications:
  email:
    recipients:
    - dilawar.s.rajput@gmail.com
    on_success: change
    on_failure: always

script:
  - brew install python@3
  - brew link --overwrite python@3
  - brew tap dilawar/moose
  - brew install moose
  - brew install --HEAD moose-nightly
  - /usr/local/bin/python3 -c "import moose; print(dir(moose))"
  - set +e
